BrookstoneCkInFinal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static, serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dashboard.urls')),
    path('ParentPortal/', include('ParentPortal.urls')),
    path('CheckIn/', include('CheckIn.urls')),
    path('Pass/', include('Pass.urls')),
    path('importStudentLists/', include('importStudentLists.urls')),
    path('importStudentLists/importTemplate', include('importStudentLists.urls')),
    path('importStudentLists/test', include('importStudentLists.urls')),
    path('Manager/', include('Manager.urls')),
    path('Manager/changeCurrentSeason', include('Manager.urls')),
    path('StudentManager/', include('StudentManager.urls')),
    path('register/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
                       serve, { 'document_root': settings.MEDIA_ROOT, }),]

Dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='Dashboard-home'),
    path('RegisterStaff/', views.sendStaffMail, name="Dashboard-SendStaffMail"),
    path('test/', views.test, name="Dashboard-test"),
]

Pass/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.viewStudentsList, name='Pass-viewStudentsList'),
    path('viewCheckInProfile/<int:pk>', views.viewCheckInProfile, name='Pass-viewCheckInProfile'),
    path('viewCheckInProfileAdmin/<int:pk>', views.viewCheckInProfileAdmin, name='Pass-viewCheckInProfile'),
    path('Pass/<int:pk>', views.Pass, name="Pass-Pass"),
    path('Pass_Admin/', views.viewStudentsListAdmin, name="Pass-viewStudentsListAdmin"),
    path('Pass_Admin/<int:pk>', views.PassAdmin, name="Pass-PassAdmin"),
]

Dashboard/models.py
from django.db import models
from StudentManager.models import Students

class PrincipalInbox(models.Model):
    student = models.ForeignKey(Students, verbose_name="Student", on_delete=models.CASCADE)
    viewed = models.CharField(max_length=4, verbose_name="Viewed", null=True, blank=True)
    approved = models.CharField(max_length=4, verbose_name="Approved", null=True, blank=True)

Dashboard/forms.py
from django import forms
from StudentManager.models import Students

class staffForm(forms.Form):
    FirstName = forms.CharField(label='First Name', max_length=50, required=True)
    LastName = forms.CharField(label='Last Name', max_length=50, required=True)
    Email = forms.EmailField(label='Email', max_length=100, required=True)


class FilterStudentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FilterStudentsForm, self).__init__(*args, **kwargs)
        self.fields['LastName'].required = False
        self.fields['FirstName'].required = False
        self.fields['ClassName'].required = False

    class Meta:
        model = Students
        fields = ('LastName', 'FirstName', 'ClassName')
        fields = ('LastName', 'FirstName', 'ClassName')

Dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import staffForm
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from smtplib import SMTPException
from django.urls import reverse
from django.contrib import messages
from StudentManager.models import Students
from .models import PrincipalInbox
from StudentManager.functions import FilterStudents
from StudentManager.forms import FilterStudentsForm
import concurrent.futures
import threading
from .functions import viewCheckInList
from django.contrib.auth.decorators import login_required
from StudentManager.models import Seasons, CurrentSeason, CheckIn
from Dashboard import decorators
from django.contrib.auth.models import Permission
from .decorators import admin

# Create your views here.
@login_required(login_url='login')
def homepage(request):
    season = Seasons.objects.get(SeasonName=CurrentSeason.objects.get(id=1).Season)
    return render(request, 'dashboard.html',
                  {'checkedins': CheckIn.objects.all().filter(Season=season).order_by('Student__LastName'),
                   'Season': Seasons.objects.get(SeasonName=CurrentSeason.objects.get(id=1).Season)})

#@user_passes_test(lambda u: Group.objects.get(name='administrator') in u.groups.all())
@login_required(login_url='login')
@admin
def sendStaffMail(request):
    if request.method == 'POST':
        #print("sendstaffmail" + str(Group.objects.get(id=1)))
        form = staffForm(request.POST)
        if form.is_valid():
            first_name = str(form.cleaned_data['FirstName'])
            last_name = str(form.cleaned_data['LastName'])
            email = str(form.cleaned_data['Email'])
            html_message = render_to_string('staffEmailForm.html', {
                'link': request.build_absolute_uri(reverse('users-register')), 'FirstName': first_name,
                'LastName': last_name, 'Email': email})
            plain_message = strip_tags(html_message)
            try:
                send_mail('Brookstone School Staff Registration',
                          plain_message,
                          'wagbarafranklin@yahoo.com',
                          ['wagbarafranklin@yahoo.com'],
                          html_message=html_message,
                          fail_silently=False)
                messages.success(request, "Email sent Successfully!")
            except SMTPException:
                messages.error(request, SMTPException)
            return render(request, 'FeedBack.html')
    else:
        form = staffForm()
    return render(request, 'registerStaff.html',
                  {'form': form})

def test(request):
    return render(request, "test.html")

Dashboard/templates/FeedBack.html
{% extends "base.html" %}
    {% load static %}
{% block head %}
{% endblock %}
{% block style %}

{% endblock %}
{% block content %}

{% endblock %}
{% block script %}

{% endblock %}

Dashboard/templates/base.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">

    {% block head %}
    {% endblock %}
</head>
{% block style %}
{% endblock %}
<body>
    <div class="container-fluid" style="background-color: #6639ad; border-bottom-style: solid; border-bottom-color: #dd05e0;">
        <div class="row" style="max-height: 50px;">
            <div class="col-md-3 col-lg-3">

            </div>
            <div class="col-8 p-3 mx-auto">
                <div class="d-none d-md-inline-block d-lg-inline-block mr-5" >
                    <img class="mb-2" src="/media/logo.jpg" alt="Joh" style="width: 40px; height: 40px;"/>
                </div>
                <div class="d-inline-block">
                  <h2 style="color: white; display: inline-block;">BROOKSTONE</h2><small class="d-none d-md-inline-block d-lg-inline-block alert-primary p-1"><i>CHECK-IN</i></small>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col mr-auto">
                <a class="btn btn-primary d-none d-md-inline-block" href="/ ">Home</a>
                <a class="btn btn-outline-primary float-right d-none d-md-inline-block" href="{% url 'logout' %}">({{user}})Logout</a>
            </div>
        </div>
    </div>

    <div class="container-fluid row">
        <div class="col-sm-6 col-md-2 col-lg-2 col-xl-2 bg-light border-right border-primary p-2" style="background-color: #dcf9f9;">
                <nav class="navbar navbar-expand-sm bg-primary navbar-dark d-md-none d-lg-none d-xl-none">
                    <div class="container">
                        <button class="navbar-toggler" data-toggle="collapse" data-target="#main">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </nav>
            <div class="btn-group-vertical btn-block navbar-collapse" id="main">
                {% if perms.StudentManager.view_admin or perms.StudentManager.view_account %}
                    <button type="button" class="btn btn-primary  active dropdown-toggle m-1 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;" data-toggle="collapse" data-target="#mainNav">
                        Students
                    </button>
                    <div class="collapse navbar-collapse text-truncate" id="mainNav">
                        <div class="navbar-nav text-center">
                            <a class="nav-item nav-link active" href="/StudentManager"><span class="text-wrap">Manage Records</span></a>

                            {% if perms.StudentManager.view_admin or perms.StudentManager.view_schooladmin %}
                                <a class="nav-item nav-link" href="/importStudentLists/importTemplate"><span class="text-wrap">Upload Excel File</span></a>
                                <a class="nav-item nav-link" href="/StudentManager/viewAddStudent"><span class="text-wrap">Add new Student</span></a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% if perms.StudentManager.view_admin %}
                    <button type="button" class="btn btn-primary dropdown-toggle m-1 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;" data-toggle="collapse" data-target="#mainNav2">
                       Manager
                    </button>
                    <div class="collapse navbar-collapse" id="mainNav2">
                        <div class="navbar-nav text-center">
                            <a class="nav-item nav-link active" href="/Manager/viewSettings"><span class="text-wrap">View Settings</span></a>
                            <a class="nav-item nav-link" href="/Manager/"><span class="text-wrap">Create CheckIn/Out Season</span></a>
                            <a class="nav-item nav-link" href="/Manager/changeCurrentSeason"><span class="text-wrap">Change Season</span></a>
                        </div>
                    </div>
                {% endif %}

                {% if perms.StudentManager.view_account %}
                    <a type="button" href="/Pass/Pass_Admin" class="btn btn-primary  m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Gate Pass(Admin)
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_gate %}
                    <a type="button" href="/Pass" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Gate Pass
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_pastoral %}
                    <a type="button" href="/CheckIn" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Check-In(PC)
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_admin %}
                    <a type="button" href="/principal_inbox/" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Inbox
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_admin %}
                    <a type="button" href="/ParentPortal" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Parent Form
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_admin %}
                    <a type="button" href="/RegisterStaff" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Staff Registration
                    </a>
                {% endif %}

                {% if perms.StudentManager.view_admin %}
                    <a type="button" href="/checkout" class="btn btn-primary m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                        Check-Out
                    </a>
                {% endif %}
            </div>
        </div>
      <div class="col-10" style="border-left-style: solid; border-top-style: solid; border-width: 10px;border-color: #03a9f4;">
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        {% block content %}

        {% endblock %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap4.min.js"></script>
<script>
$(document).ready(function () {
$('#example').DataTable({
"scrollX": true,
"scrollY": 500,
});
$('.dataTables_length').addClass('bs-select');
});
</script>
</body>
</html>

Dashboard/templates/boot.html
<!DOCTYPE html>
<html lang="en">
  <head>
       <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="bootstrap-4.5.2-dist/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  </head>
<body>
  <div class="container-fluid" style="background-color: #6639ad; border-bottom-style: solid; border-bottom-color: #dd05e0;">
    <div class="row" style="max-height: 50px;">
        <div class="col-md-3 col-lg-3">

        </div>
        <div class="col-8 p-3 mx-auto">
            <div class="d-none d-md-inline-block d-lg-inline-block mr-5" >
                <img class="mb-2" src="logo.jpg" alt="Joh" style="width: 40px; height: 40px;"/>
            </div>
            <div class="d-inline-block">
              <h2 style="color: white; display: inline-block;">BROOKSTONE</h2><small class="d-none d-md-inline-block d-lg-inline-block alert-primary p-1"><i>CHECK-IN</i></small>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col mr-auto">
            <a class="btn btn-primary d-none d-md-inline-block" href="/ ">Home</a>
            <a class="btn btn-outline-primary float-right d-none d-md-inline-block" href="{% url 'logout' %}">({{user}})Logout</a>
        </div>
    </div>
  </div>
  <div class="container-fluid row">
        <div class="col-sm-6 col-md-2 col-lg-2 col-xl-2 bg-light border-right border-primary p-2" style="background-color: #dcf9f9;">
                <nav class="navbar navbar-expand-sm bg-primary navbar-dark d-md-none d-lg-none d-xl-none">
                    <div class="container">
                        <button class="navbar-toggler" data-toggle="collapse" data-target="#main">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </nav>
            <div class="btn-group-vertical btn-block navbar-collapse" id="main">
              <button type="button" class="btn btn-primary navbar-toggler active dropdown-toggle m-1 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;" data-toggle="collapse" data-target="#mainNav">
                  Students
              </button>
                <div class="collapse navbar-collapse text-truncate" id="mainNav">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="/StudentManager"><span class="text-wrap">Manage Records</span></a>
                        <a class="nav-item nav-link" href="/importStudentLists/importTemplate"><span class="text-wrap">Upload Excel File</span></a>
                        <a class="nav-item nav-link" href="/StudentManager/viewAddStudent"><span class="text-wrap">Add new Student</span></a>
                        <a class="nav-item nav-link" href="#"><span class="text-wrap">Aboufsfsfsfsfsf sfsfsfsfsffsft</span></a>
                    </div>
                </div>

                <button type="button" class="btn btn-primary navbar-toggler dropdown-toggle m-1 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;" data-toggle="collapse" data-target="#mainNav2">
                   Manager
                </button>
                <div class="collapse navbar-collapse" id="mainNav2">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="/Manager/ViewSettings"><span class="text-wrap">View Settings</span></a>
                        <a class="nav-item nav-link" href="/Manager/"><span class="text-wrap">Create CheckIn/Out Season</span></a>
                        <a class="nav-item nav-link" href="/Manager/setCurrentSeason"><span class="text-wrap">Change Season</span></a>
                        <a class="nav-item nav-link" href="#"><span class="text-wrap">Aboufsfsfsfsfsf sfsfsfsfsffsft</span></a>
                    </div>
                </div>
                <a type="button" href="/viewCheckIn_Admin" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Check-In(Admin)
                </a>
                <a type="button" href="/viewCheckIn" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Check-In
                </a>
                <a type="button" href="/principal_inbox/" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Inbox
                </a>
                <a type="button" href="/CreateParentForm" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Parent Form
                </a>
                <a type="button" href="/RegisterStaff" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Staff Registration
                </a>
                <a type="button" href="/checkout" class="btn btn-primary navbar-toggler m-1 p-2 border-0" style="background-color:#03a9f4; height: 40px; border-radius: 0px;">
                    Check-Out
                </a>
            </div>
        </div>
      <div class="col-10">

      </div>
  </div>

  <script src="jquery-3.5.1.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="bootstrap-4.5.2-dist/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

Dashboard/templates/dashboard.html
{% extends "base.html" %}
    {% load static %}
{% load bootstrap4 %}
{% block head %}
    <title>BrookStone</title>
{% endblock %}
{% block style %}
    <style>
        .table-main th {
        background-color: #00ff1f;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="piechart"></div>

    <script src="https://www.gstatic.com/charts/loader.js" type="text/javascript"></script>

    <script type="text/javascript">
        // Load google charts
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        // Draw the chart and set the chart values
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                    ['Task', "Today's Check-In"],
                    ['Checked-In', {{ Season.TotalCheckIn }}],
                    ['Not Checked-In', {{ Season.TotalNotCheckIn }}]
                    ]);

            // Optional; add a title and set the width and height of the chart
            var options = {'title':"Today's Check-In Summary", 'width':550, 'height':400};

            // Display the chart inside the <div> element with id="piechart"
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }
    </script>
    <script>
        /*window.onload = function () {
            var plot = [{y: 300}, {y: 380}, {y: 200}, {y: 400}, {y: 700},
             {y: 3000}, {y: 500}, {y: 340}, {y: 560}, {y: 390}, {y: 700}]
            var chart = new CanvasJS.Chart("chartContainer", { animationEnabled: true, theme: "light2",
                      title:{ text: "Simple Line Chart" }, axisY:{ includeZero: false },
                      data: [{ type: "line", dataPoints: plot }]
                      });
            chart.render();

        }*/
    </script>
    <!--<div id="chartContainer" style="height: 300px; width: 100%;"></div>--!>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <div>
            <div class="container mb-3 mt-3">
            <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>SID</th>
                        <th>LastName</th>
                        <th>FirstName</th>
                        <th>MiddleName</th>
                        <th>Gender</th>
                        <th>ClassName</th>
                        <th>Gate Pass</th>
                        <th>Checked In</th>
                        <th>Checked-In By</th>
                        <th>Reason for Allowing</th>
                    </tr>
                </thead>

                <tbody >
                {% for cin in checkedins %}
                    <tr>
                        <td><b>{{ forloop.counter }}</b></td>
                        <td>{{ cin.Student.LastName }}</td>
                        <td>{{ cin.Student.FirstName }}</td>
                        <td>{{ cin.Student.MiddleName }}</td>
                        <td>{{ cin.Student.Gender }}</td>
                        <td>{{ cin.Student.ClassName }}</td>
                        {% if cin.Passed == "Yes" %}
                            <td style="background-color: green; color: white;">Passed</td>
                        {% else %}
                            <td style="background-color: red; color: white;">No</td>
                        {% endif %}
                        {% if cin.CheckedIn == "Yes" %}
                            <td style="background-color: green; color: white;">Checked-In</td>
                        {% else %}
                            <td style="background-color: red; color: white;">No</td>
                        {% endif %}
                        <td>{{ cin.ByStaffCheckIn }}</td>
                        <td>
                            {% if cin.CheckedIn == "No" %}
                                {{ cin.ReasonPass }}
                            {% else %}
                                {{ cin.ReasonCheckInPC }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
            </div>
        </div>
{% endblock %}

Dashboard/templates/formalbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/dashboard.css' %}"/>
    {% block head %}
    {% endblock %}
</head>
{% block style %}
{% endblock %}
<body>
<div class="nav">
    <div class="logo"><img src="/media/logo.jpg" alt="Joh" style="width:100%; height: 100%"></div>
    <ul><h2>BROOKSTONE <span><i>CHECK-IN</i></span></h2>
        <li><a class="active" href="/ ">Home</a></li>
        <li style="float:right"><a href="{% url 'logout' %}">({{user}})Logout</a></li>
    </ul>
</div>
<div class="container">
    <div class="side-nav">
        <ul class="side-nav-ul">
            {% if perms.dashboard.view_principalinbox or perms.dashboard.view_staffs or perms.admin.view_logentry%}
            <li><a href="/viewStudents">Students</a>
                <ul>
                    <li><a href="/StudentManager">Manage Records</a></li>
                    <li><a href="/importStudentLists/importTemplate">Upload Excel File</a></li>
                    <li><a href="/StudentManager/viewAddStudent">Add new Student</a></li>
                </ul>
            </li>
            <li><a href="/Manager/ViewSettings">Manager</a>
                <ul>
                    <li><a href="/Manager/ViewSettings">View Settings</a></li>
                    <li><a href="/Manager/">Create CheckIn/Out Season</a></li>
                    <li><a href="/Manager/setCurrentSeason">Change Season</a></li>
                </ul>
            </li>
            <li><a href="/viewCheckIn_Admin">Check-In(Admin)</a></li>
            <li><a href="/checkout">Check-Out</a></li>
            {% else %}
            <li><a href="/viewCheckIn">Check-In</a></li>
            <li><a href="/checkout">Check-Out</a></li>
            {% endif %}
            {% if perms.dashboard.view_principalinbox %}
            <li><a href="/principal_inbox/">Inbox</a></li>
            {% endif %}
            {% if perms.admin.view_logentry %}
            <li><a href="/CreateParentForm">Parent Form</a></li>
            <li><a href="/RegisterStaff">Staff Registration</a></li>
            <li><a href="/viewCheckIn">Check-In</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="content">
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p style="background-color: green; color: white; padding: 5px;">{{ message }}</p>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <p style="background-color: red; color: white; padding: 5px;"> {{ message }}</p>
            {% endif %}
        {% endfor %}
            {% block content %}
            {% endblock %}
    </div>
    {% block script %}
    {% endblock %}
</div>
</body>
</html>

Dashboard/templates/registerStaff.html
{% extends "base.html" %}
    {% load static %}
{% load bootstrap4 %}
{% block head %}

{% endblock %}
{% block style %}

{% endblock %}
{% block content %}
    <div class="view-form">
        <form method="POST" class="p-4 w-50">
            {% csrf_token %}
            {% bootstrap_form form layout='inline'%}
            {% buttons %}
            <button class="btn btn-primary" type="submit" value="save">Send</button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

Dashboard/templates/staffEmailForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Brookstone School Staff Registration</title>
</head>
<body>
    <p>Hi Mr. {{ LastName }},</p>
    <p>Please follow this <a href="{{ link }}">Link: </a></p>
    <p>{{ link }}</p>
    <p>To create your account on the Brookstone Check-in portal.</p>
    <p>Thank you.</p>
    <p>`I.C.T Department</p>
</body>
</html>